[[plugins]] # airline
 repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts=1
'''

[[plugins]] # airline
 repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme="badwolf"
'''

[[plugins]] 
repo = 'junegunn/vim-easy-align'

[[plugins]] 
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
noremap <silent><C-p> :FZF<CR>
noremap <silent><C-f> :Ag<CR>
command! -bang -nargs=* MRU call fzf#vim#history(fzf#vim#with_preview())
'''


[[plugins]]
repo = 'francoiscabrol/ranger.vim'
hook_add = '''
map <silent><leader>f :Ranger<CR>
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = '''
let g:coc_global_extensions = [
	\'coc-ccls',
	\'coc-css',
	\'coc-emmet',
	\'coc-explorer',
	\'coc-flutter',
	\'coc-git',
	\'coc-gitignore',
	\'coc-go',
	\'coc-html',
	\'coc-json',
	\'coc-lists',
	\'coc-pairs',
	\'coc-pyright',
	\'coc-python',
	\'coc-rls',
	\'coc-rust-analyzer',
	\'coc-sourcekit',
	\'coc-stylelint',
	\'coc-tailwindcss',
	\'coc-translator',
	\'coc-tslint',
	\'coc-tsserver',
	\'coc-vimlsp',
	\'coc-yank',
	\]
nnoremap <silent> <space>y :<C-u>CocList -A --normal yank<CR>
noremap <silent><F3> :CocCommand explorer<CR>
'''

[[plugins]]
repo = 'Yggdroot/LeaderF'
build =  './install.sh'
hook_add = '''
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_PreviewResult = {'Function':0, 'Colorscheme':1}
let g:Lf_NormalMap = {
  \ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']],
  \ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<CR>']],
  \ "Mru":    [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<CR>']],
  \ "Tag":    [["<ESC>", ':exec g:Lf_py "tagExplManager.quit()"<CR>']],
  \ "Function":    [["<ESC>", ':exec g:Lf_py "functionExplManager.quit()"<CR>']],
  \ "Colorscheme":    [["<ESC>", ':exec g:Lf_py "colorschemeExplManager.quit()"<CR>']],
  \ }

let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagslabel = 'native-pygments'
let g:Lf_ReverseOrder = 1
noremap <silent><F4> :Leaderf! file<CR>
noremap <silent><F6> :LeaderfFunction!<CR>
noremap <silent><leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <silent><leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <silent><leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
noremap <silent><leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
noremap <silent><leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>
noremap <silent><leader>ff :<C-U><C-R>=printf("Leaderf! rg  %s", expand("<cword>"))<CR><CR>
'''

[[plugins]] # c/c++ header
repo = 'Shougo/neoinclude.vim'

[[plugins]] # colorscheme
repo = 'dracula/vim'
name = 'dracula'
hook_add = '''
colorscheme dracula
'''

[[plugins]]
repo = 'cpiger/NeoDebug'

[[plugins]] # snippets
repo = 'sirver/ultisnips'
hook_add = '''
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
'''

[[plugins]] # snippets
repo = 'honza/vim-snippets'

[[plugins]] # () [] {} color
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]] #syntax
repo = 'sheerun/vim-polyglot'

[[plugins]] # cmake
repo = 'huleiak47/vim-cmake-complete'

[[plugins]] # startup
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

